apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv-volume
  namespace: sonarqube
spec:
  capacity:
    storage: 10Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonar-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9e89bd602ca1148::fsap-02f63a07dfe90a41c  # Replace with your EFS File System ID

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-pvc
  namespace: sonarqube
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi  # This should match the size in the PV
  storageClassName: sonar-sc

